#!/usr/bin/env python3
"""Connect the VoxCPM2 Voice Server to Open WebUI (its built-in "OpenAI" text-to-speech engine).

Open WebUI is usually run in Docker, so this writes an env file you pass to the container and prints the
settings for the Admin panel. Inside Docker, 127.0.0.1 is the container itself, so the URL becomes
http://host.docker.internal:<port>/v1 and the voice server must listen on the network (VOXCPM_HOST=0.0.0.0).

    python integrations/open_webui/install.py                 # Docker (default)
    python integrations/open_webui/install.py --no-docker     # Open WebUI installed with pip on this machine
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from common import ROOT, base_parser, fetch_voices, finish_args, ok, say, server_check, settings, warn  # noqa: E402

ENV_FILE = ROOT / "integrations" / "open_webui" / "open-webui-tts.env"


def main(argv=None) -> int:
    p = base_parser("Connect the VoxCPM2 Voice Server to Open WebUI")
    p.add_argument("--no-docker", action="store_true", help="Open WebUI runs directly on this computer")
    p.add_argument("--voice", help="voice id (default: the server's default voice)")
    args = finish_args(p.parse_args(argv))
    say("\n== Open WebUI ==")
    if args.uninstall:
        if ENV_FILE.exists() and not args.dry_run:
            ENV_FILE.unlink()
        ok("Removed the env file. In Open WebUI: Admin Panel > Settings > Audio > Text-to-Speech Engine > Web API.")
        return 0

    server_check(args)
    port = args.server_url.rsplit(":", 1)[-1].split("/")[0]
    base = f"http://127.0.0.1:{port}/v1" if args.no_docker else f"http://host.docker.internal:{port}/v1"
    voices = fetch_voices(args.server_url, args.api_key)
    voice = args.voice or next((v["voice_id"] for v in voices if v.get("default")), "vox-aura-studio")
    lines = ["# Open WebUI -> VoxCPM2 Voice Server (generated by integrations/open_webui/install.py)",
             "AUDIO_TTS_ENGINE=openai",
             f"AUDIO_TTS_OPENAI_API_BASE_URL={base}",
             f"AUDIO_TTS_OPENAI_API_KEY={args.api_key or 'not-needed'}",
             "AUDIO_TTS_MODEL=voxcpm2",
             f"AUDIO_TTS_VOICE={voice}",
             "AUDIO_TTS_SPLIT_ON=punctuation", ""]
    if args.dry_run:
        say("  (dry run) would write " + str(ENV_FILE) + ":\n" + "\n".join(lines))
    else:
        ENV_FILE.write_text("\n".join(lines), encoding="utf-8")
        ok(f"wrote {ENV_FILE}")

    if not args.no_docker:
        try:
            host = settings().host
        except Exception:  # noqa: BLE001
            host = "127.0.0.1"
        if host in ("127.0.0.1", "localhost"):
            warn("The voice server only listens on 127.0.0.1, which Docker containers cannot reach. "
                 "Set VOXCPM_HOST=0.0.0.0 in .env (and ideally VOXCPM_API_KEY), then restart the server.")
        say("\n  New container:")
        say(f'    docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway --env-file "{ENV_FILE}" \\')
        say("      -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:main")
        say("  Existing container: these env vars only apply on first start (Open WebUI saves settings in its database),")
        say("  so set them in the browser instead:")
    else:
        say("\n  Start Open WebUI with this env file loaded, or set it in the browser:")
    say("    Admin Panel > Settings > Audio > Text-to-Speech")
    say(f"      Engine: OpenAI   URL: {base}   Key: {args.api_key or 'not-needed'}")
    say(f"      Model: voxcpm2   Voice: {voice}")
    say("  Then click the speaker icon under any reply (or enable auto-playback in Settings > Audio).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
